# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Bike Availablity

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
      - cron: "13 * * * *" #runs every hour at minute 13 UTC everyday

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run script
      run: |
        python main.py
      env:
        URLS: ${{ secrets.URLS }}
    - name: Deploy
      uses: exuanbo/actions-deploy-gist@v1.1.2
      with:
        token: ${{ secrets.GIST }}
        gist_id: 8cbc717a8538036da5deb82a915c5a44
        gist_description: "Get-That-Bike Log"
        gist_file_name: example.log
        file_path: ./example.log